export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const SET_ALL_TASKS = 'SET_ALL_TASKS';

export const TOGGLE_TASK_STATUS = 'TOGGLE_TASK_STATUS';
export const TOGGLE_TASK_STATUS_SUCCESS = 'TOGGLE_TASK_STATUS_SUCCESS';
export const TOGGLE_TASK_STATUS_FAILURE = 'TOGGLE_TASK_STATUS_FAILURE';
