
export const TOGGLE_TASK_STATUS = 'TOGGLE_TASK_STATUS';
export const TOGGLE_TASK_STATUS_SUCCESS = 'TOGGLE_TASK_STATUS_SUCCESS';
export const TOGGLE_TASK_STATUS_FAILURE = 'TOGGLE_TASK_STATUS_FAILURE';
export const GET_ALL_TASKS_BY_USER_ID = 'GET_ALL_TASKS_BY_USER_ID';
export const SET_ALL_TASKS_BY_USER_ID = 'SET_ALL_TASKS_BY_USER_ID';
export const DELETE_TASK_BY_ID = 'DELETE_TASK_BY_ID';
