export const CREATE_TASK = 'TASK_REQUEST';
export const UPDATE_TAKS = 'UPDATE_TASK';
// export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
// export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';
export const SET_NEW_TASK = 'SET_NEW_TASK';
export const SET_UPDATE_TASK = 'SET_UPDATE_TASK';
export const RESET_ADD_TASK = 'RESET_ADD_TASK';
